---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: app
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      serviceAccountName: demo-app-sa # Must have access to Secret Manager
      containers:
        - name: test-app
          image: asia-south1-docker.pkg.dev/shared-vpc-service-315/prod-python-app/prod-app:v1-56c85ae-20250627145539
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: secrets-store
              mountPath: "/var/secrets"
              readOnly: true
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "demo-app-spc"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: app
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: http
  selector:
    app: mysql
---

